************* Module New-test
__init__.py:1:0: C0103: Module name "New-test" doesn't conform to snake_case naming style (invalid-name)
__init__.py:10:0: E0401: Unable to import 'project.config.configuration' (import-error)
__init__.py:11:0: E0401: Unable to import 'project.utils.logging_utils' (import-error)
************* Module New-test.console
console.py:14:0: E0401: Unable to import 'project.config' (import-error)
console.py:15:0: E0401: Unable to import 'project.utils.logging_utils' (import-error)
console.py:16:0: E0401: Unable to import 'project.data.market_data' (import-error)
console.py:17:0: E0401: Unable to import 'project.trade_executor.order_executor' (import-error)
console.py:18:0: E0401: Unable to import 'project.bots.bot_manager' (import-error)
console.py:19:0: E0401: Unable to import 'project.bots.strategies.strategy_manager' (import-error)
console.py:20:0: E0401: Unable to import 'project.bots.arbitrage.core' (import-error)
console.py:21:0: E0401: Unable to import 'project.bots.arbitrage.multi_exchange' (import-error)
console.py:22:0: E0401: Unable to import 'project.api.rest_api' (import-error)
console.py:23:0: E0401: Unable to import 'project.utils.notify' (import-error)
console.py:35:0: C0103: Constant name "api_runner" doesn't conform to UPPER_CASE naming style (invalid-name)
console.py:82:22: W0613: Unused argument 'arg' (unused-argument)
console.py:91:4: R0914: Too many local variables (16/15) (too-many-locals)
console.py:91:4: R0912: Too many branches (16/12) (too-many-branches)
console.py:226:18: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
console.py:307:22: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
console.py:239:4: R0912: Too many branches (18/12) (too-many-branches)
console.py:239:4: R0915: Too many statements (59/50) (too-many-statements)
console.py:418:22: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
console.py:353:4: R0912: Too many branches (17/12) (too-many-branches)
console.py:353:4: R0915: Too many statements (58/50) (too-many-statements)
console.py:545:22: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
console.py:468:4: R0912: Too many branches (18/12) (too-many-branches)
console.py:468:4: R0915: Too many statements (68/50) (too-many-statements)
console.py:616:8: W0603: Using the global statement (global-statement)
console.py:637:24: W0612: Unused variable 'site' (unused-variable)
console.py:711:4: C0415: Import outside toplevel (logging) (import-outside-toplevel)
console.py:7:0: W0611: Unused datetime imported from datetime (unused-import)
console.py:12:0: W0611: Unused import time (unused-import)
************* Module New-test.fix_project
fix_project.py:79:0: C0301: Line too long (113/100) (line-too-long)
fix_project.py:106:15: W0718: Catching too general exception Exception (broad-exception-caught)
fix_project.py:130:15: W0718: Catching too general exception Exception (broad-exception-caught)
fix_project.py:150:11: W0718: Catching too general exception Exception (broad-exception-caught)
************* Module New-test.config
config.py:8:0: E0401: Unable to import 'pydantic' (import-error)
config.py:9:0: E0401: Unable to import 'pydantic_settings' (import-error)
config.py:10:0: E0401: Unable to import 'dotenv' (import-error)
config.py:22:0: R0903: Too few public methods (0/2) (too-few-public-methods)
config.py:31:0: R0903: Too few public methods (0/2) (too-few-public-methods)
config.py:48:4: E0213: Method 'parse_allowed_users' should have "self" as first argument (no-self-argument)
config.py:40:0: R0903: Too few public methods (1/2) (too-few-public-methods)
config.py:55:0: R0903: Too few public methods (0/2) (too-few-public-methods)
config.py:66:0: R0903: Too few public methods (0/2) (too-few-public-methods)
config.py:75:0: R0903: Too few public methods (0/2) (too-few-public-methods)
config.py:95:0: R0903: Too few public methods (0/2) (too-few-public-methods)
config.py:116:0: R0903: Too few public methods (0/2) (too-few-public-methods)
config.py:163:4: R0903: Too few public methods (0/2) (too-few-public-methods)
config.py:177:8: R1705: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)
config.py:229:0: C0103: Constant name "_config_instance" doesn't conform to UPPER_CASE naming style (invalid-name)
config.py:240:4: W0603: Using the global statement (global-statement)
************* Module New-test.exchange.exchange_manager
exchange/exchange_manager.py:1:0: C0302: Too many lines in module (2371/1000) (too-many-lines)
exchange/exchange_manager.py:1:0: C0114: Missing module docstring (missing-module-docstring)
exchange/exchange_manager.py:14:0: E0401: Unable to import 'ccxt.async_support' (import-error)
exchange/exchange_manager.py:15:0: E0401: Unable to import 'project.utils.error_handler' (import-error)
exchange/exchange_manager.py:16:0: E0401: Unable to import 'project.utils.logging_utils' (import-error)
exchange/exchange_manager.py:17:0: E0401: Unable to import 'project.utils.websocket_client' (import-error)
exchange/exchange_manager.py:61:0: R0902: Too many instance attributes (15/7) (too-many-instance-attributes)
exchange/exchange_manager.py:61:0: R0903: Too few public methods (1/2) (too-few-public-methods)
exchange/exchange_manager.py:146:0: R0902: Too many instance attributes (9/7) (too-many-instance-attributes)
exchange/exchange_manager.py:418:0: R0902: Too many instance attributes (12/7) (too-many-instance-attributes)
exchange/exchange_manager.py:528:23: W0718: Catching too general exception Exception (broad-exception-caught)
exchange/exchange_manager.py:544:19: W0718: Catching too general exception Exception (broad-exception-caught)
exchange/exchange_manager.py:634:15: W0718: Catching too general exception Exception (broad-exception-caught)
exchange/exchange_manager.py:574:23: W0718: Catching too general exception Exception (broad-exception-caught)
exchange/exchange_manager.py:604:12: W0612: Unused variable 'conn_id' (unused-variable)
exchange/exchange_manager.py:745:8: R1705: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)
exchange/exchange_manager.py:818:8: R1705: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)
exchange/exchange_manager.py:820:57: W0613: Unused argument 'url' (unused-argument)
exchange/exchange_manager.py:833:55: W0613: Unused argument 'url' (unused-argument)
exchange/exchange_manager.py:904:27: C0201: Consider iterating the dictionary directly instead of calling .keys() (consider-iterating-dictionary)
exchange/exchange_manager.py:917:19: W0718: Catching too general exception Exception (broad-exception-caught)
exchange/exchange_manager.py:936:8: W0602: Using global for 'exchange_instances' but no assignment is done (global-variable-not-assigned)
exchange/exchange_manager.py:1009:19: W0718: Catching too general exception Exception (broad-exception-caught)
exchange/exchange_manager.py:1051:15: W0718: Catching too general exception Exception (broad-exception-caught)
exchange/exchange_manager.py:1132:15: W0718: Catching too general exception Exception (broad-exception-caught)
exchange/exchange_manager.py:1172:15: W0718: Catching too general exception Exception (broad-exception-caught)
exchange/exchange_manager.py:1215:15: W0718: Catching too general exception Exception (broad-exception-caught)
exchange/exchange_manager.py:1268:15: W0718: Catching too general exception Exception (broad-exception-caught)
exchange/exchange_manager.py:1277:4: R0913: Too many arguments (6/5) (too-many-arguments)
exchange/exchange_manager.py:1277:4: R0917: Too many positional arguments (6/5) (too-many-positional-arguments)
exchange/exchange_manager.py:1332:15: W0718: Catching too general exception Exception (broad-exception-caught)
exchange/exchange_manager.py:1383:15: W0718: Catching too general exception Exception (broad-exception-caught)
exchange/exchange_manager.py:1422:15: W0718: Catching too general exception Exception (broad-exception-caught)
exchange/exchange_manager.py:1429:4: R0913: Too many arguments (8/5) (too-many-arguments)
exchange/exchange_manager.py:1429:4: R0917: Too many positional arguments (8/5) (too-many-positional-arguments)
exchange/exchange_manager.py:1485:15: W0718: Catching too general exception Exception (broad-exception-caught)
exchange/exchange_manager.py:1529:15: W0718: Catching too general exception Exception (broad-exception-caught)
exchange/exchange_manager.py:1570:15: W0718: Catching too general exception Exception (broad-exception-caught)
exchange/exchange_manager.py:1612:15: W0718: Catching too general exception Exception (broad-exception-caught)
exchange/exchange_manager.py:1668:15: W0718: Catching too general exception Exception (broad-exception-caught)
exchange/exchange_manager.py:1717:15: W0718: Catching too general exception Exception (broad-exception-caught)
exchange/exchange_manager.py:1770:8: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
exchange/exchange_manager.py:1785:8: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
exchange/exchange_manager.py:1855:15: W0718: Catching too general exception Exception (broad-exception-caught)
exchange/exchange_manager.py:1873:8: R1705: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)
exchange/exchange_manager.py:1882:12: W0612: Unused variable 'instrument_type' (unused-variable)
exchange/exchange_manager.py:1903:8: R1705: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)
exchange/exchange_manager.py:1952:15: W0718: Catching too general exception Exception (broad-exception-caught)
exchange/exchange_manager.py:1972:8: R1705: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)
exchange/exchange_manager.py:2038:15: W0718: Catching too general exception Exception (broad-exception-caught)
exchange/exchange_manager.py:2059:8: R1705: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)
exchange/exchange_manager.py:2088:8: R1705: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)
exchange/exchange_manager.py:2131:15: W0718: Catching too general exception Exception (broad-exception-caught)
exchange/exchange_manager.py:2140:4: R0913: Too many arguments (7/5) (too-many-arguments)
exchange/exchange_manager.py:2140:4: R0917: Too many positional arguments (7/5) (too-many-positional-arguments)
exchange/exchange_manager.py:2190:15: W0718: Catching too general exception Exception (broad-exception-caught)
exchange/exchange_manager.py:2239:15: W0718: Catching too general exception Exception (broad-exception-caught)
exchange/exchange_manager.py:2286:15: W0718: Catching too general exception Exception (broad-exception-caught)
exchange/exchange_manager.py:2323:15: W0718: Catching too general exception Exception (broad-exception-caught)
exchange/exchange_manager.py:2332:26: E1101: Instance of 'ExchangeManager' has no 'exchanges' member (no-member)
exchange/exchange_manager.py:2334:28: E1101: Instance of 'ExchangeManager' has no 'paper_trading_exchanges' member (no-member)
exchange/exchange_manager.py:2335:19: E1101: Instance of 'ExchangeManager' has no 'paper_trading_exchanges' member (no-member)
exchange/exchange_manager.py:2330:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
exchange/exchange_manager.py:418:0: R0904: Too many public methods (31/20) (too-many-public-methods)
exchange/exchange_manager.py:2341:0: C0103: Constant name "_exchange_manager" doesn't conform to UPPER_CASE naming style (invalid-name)
exchange/exchange_manager.py:2351:4: W0603: Using the global statement (global-statement)
exchange/exchange_manager.py:5:0: W0611: Unused import json (unused-import)
exchange/exchange_manager.py:6:0: W0611: Unused import logging (unused-import)
exchange/exchange_manager.py:7:0: W0611: Unused import os (unused-import)
exchange/exchange_manager.py:8:0: W0611: Unused import random (unused-import)
exchange/exchange_manager.py:10:0: W0611: Unused import uuid (unused-import)
exchange/exchange_manager.py:11:0: W0611: Unused timedelta imported from datetime (unused-import)
exchange/exchange_manager.py:12:0: W0611: Unused Set imported from typing (unused-import)
exchange/exchange_manager.py:12:0: W0611: Unused Union imported from typing (unused-import)
exchange/exchange_manager.py:15:0: W0611: Unused ExchangeErrorHandler imported from project.utils.error_handler (unused-import)
exchange/exchange_manager.py:15:0: W0611: Unused handle_exchange_errors imported from project.utils.error_handler (unused-import)
exchange/exchange_manager.py:17:0: W0611: Unused WebSocketClient imported from project.utils.websocket_client (unused-import)
************* Module New-test.exchange.exchange_errors
exchange/exchange_errors.py:1:0: C0114: Missing module docstring (missing-module-docstring)
exchange/exchange_errors.py:2:0: E0401: Unable to import 'ccxt' (import-error)
exchange/exchange_errors.py:3:0: E0401: Unable to import 'project.utils.logging_utils' (import-error)
exchange/exchange_errors.py:68:12: C0415: Import outside toplevel (re) (import-outside-toplevel)
exchange/exchange_errors.py:33:0: R0903: Too few public methods (1/2) (too-few-public-methods)
exchange/exchange_errors.py:1:0: W0611: Unused Dict imported from typing (unused-import)
exchange/exchange_errors.py:1:0: W0611: Unused Optional imported from typing (unused-import)
exchange/exchange_errors.py:1:0: W0611: Unused Type imported from typing (unused-import)
************* Module New-test.exchange.exchange_factory
exchange/exchange_factory.py:1:0: C0114: Missing module docstring (missing-module-docstring)
exchange/exchange_factory.py:3:0: E0401: Unable to import 'project.exchange.exchange_base' (import-error)
exchange/exchange_factory.py:4:0: E0401: Unable to import 'project.exchange.adapters.binance_adapter' (import-error)
exchange/exchange_factory.py:5:0: E0401: Unable to import 'project.exchange.adapters.bybit_adapter' (import-error)
exchange/exchange_factory.py:6:0: E0401: Unable to import 'project.exchange.adapters.htx_adapter' (import-error)
exchange/exchange_factory.py:7:0: E0401: Unable to import 'project.exchange.adapters.phemex_adapter' (import-error)
exchange/exchange_factory.py:8:0: E0401: Unable to import 'project.exchange.adapters.mex_adapter' (import-error)
exchange/exchange_factory.py:9:0: E0401: Unable to import 'project.utils.logging_utils' (import-error)
exchange/exchange_factory.py:47:15: W0718: Catching too general exception Exception (broad-exception-caught)
************* Module New-test.exchange.exchange_base
exchange/exchange_base.py:1:0: C0114: Missing module docstring (missing-module-docstring)
exchange/exchange_base.py:6:0: E0401: Unable to import 'project.utils.error_handler' (import-error)
exchange/exchange_base.py:7:0: E0401: Unable to import 'project.utils.logging_utils' (import-error)
exchange/exchange_base.py:37:8: W0107: Unnecessary pass statement (unnecessary-pass)
exchange/exchange_base.py:47:8: W0107: Unnecessary pass statement (unnecessary-pass)
exchange/exchange_base.py:68:15: W0718: Catching too general exception Exception (broad-exception-caught)
exchange/exchange_base.py:1:0: W0611: Unused import asyncio (unused-import)
exchange/exchange_base.py:2:0: W0611: Unused import time (unused-import)
exchange/exchange_base.py:4:0: W0611: Unused List imported from typing (unused-import)
exchange/exchange_base.py:4:0: W0611: Unused Any imported from typing (unused-import)
************* Module New-test.config.configuration
config/configuration.py:11:0: E0401: Unable to import 'project.utils.logging_utils' (import-error)
config/configuration.py:21:4: C0103: Attribute name "DATABASE_URI" doesn't conform to snake_case naming style (invalid-name)
config/configuration.py:26:4: C0103: Attribute name "API_HOST" doesn't conform to snake_case naming style (invalid-name)
config/configuration.py:27:4: C0103: Attribute name "API_PORT" doesn't conform to snake_case naming style (invalid-name)
config/configuration.py:30:4: C0103: Attribute name "WS_HOST" doesn't conform to snake_case naming style (invalid-name)
config/configuration.py:31:4: C0103: Attribute name "WS_PORT" doesn't conform to snake_case naming style (invalid-name)
config/configuration.py:34:4: C0103: Attribute name "SECRET_KEY" doesn't conform to snake_case naming style (invalid-name)
config/configuration.py:35:4: C0103: Attribute name "ENCRYPTION_KEY" doesn't conform to snake_case naming style (invalid-name)
config/configuration.py:36:4: C0103: Attribute name "AUTH_ENABLED" doesn't conform to snake_case naming style (invalid-name)
config/configuration.py:39:4: C0103: Attribute name "MESSAGE_BROKER_URI" doesn't conform to snake_case naming style (invalid-name)
config/configuration.py:44:4: C0103: Attribute name "TELEGRAM_BOT_TOKEN" doesn't conform to snake_case naming style (invalid-name)
config/configuration.py:45:4: C0103: Attribute name "TELEGRAM_CHAT_ID" doesn't conform to snake_case naming style (invalid-name)
config/configuration.py:48:4: C0103: Attribute name "BINANCE_API_KEY" doesn't conform to snake_case naming style (invalid-name)
config/configuration.py:49:4: C0103: Attribute name "BINANCE_API_SECRET" doesn't conform to snake_case naming style (invalid-name)
config/configuration.py:52:4: C0103: Attribute name "LOG_LEVEL" doesn't conform to snake_case naming style (invalid-name)
config/configuration.py:53:4: C0103: Attribute name "LOG_FORMAT" doesn't conform to snake_case naming style (invalid-name)
config/configuration.py:58:4: C0103: Attribute name "DEFAULT_COMMISSION" doesn't conform to snake_case naming style (invalid-name)
config/configuration.py:59:4: C0103: Attribute name "DEFAULT_SLIPPAGE" doesn't conform to snake_case naming style (invalid-name)
config/configuration.py:17:0: R0902: Too many instance attributes (17/7) (too-many-instance-attributes)
config/configuration.py:80:4: C0103: Attribute name "ALLOWED_USERS" doesn't conform to snake_case naming style (invalid-name)
config/configuration.py:78:4: C0103: Attribute name "CHAT_ID" doesn't conform to snake_case naming style (invalid-name)
config/configuration.py:79:4: C0103: Attribute name "BOT_TOKEN" doesn't conform to snake_case naming style (invalid-name)
config/configuration.py:117:19: W0718: Catching too general exception Exception (broad-exception-caught)
config/configuration.py:108:21: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
config/configuration.py:9:0: W0611: Unused Optional imported from typing (unused-import)
************* Module New-test.api.websocket
api/websocket.py:12:0: E0401: Unable to import 'websockets' (import-error)
api/websocket.py:13:0: E0401: Unable to import 'websockets.server' (import-error)
api/websocket.py:15:0: E0401: Unable to import 'project.config.configuration' (import-error)
api/websocket.py:16:0: E0401: Unable to import 'project.infrastructure.message_broker' (import-error)
api/websocket.py:17:0: E0401: Unable to import 'project.utils.error_handler' (import-error)
api/websocket.py:18:0: E0401: Unable to import 'project.utils.logging_utils' (import-error)
api/websocket.py:26:0: R0902: Too many instance attributes (9/7) (too-many-instance-attributes)
api/websocket.py:180:23: W0718: Catching too general exception Exception (broad-exception-caught)
api/websocket.py:130:50: W0613: Unused argument 'path' (unused-argument)
api/websocket.py:345:19: W0718: Catching too general exception Exception (broad-exception-caught)
api/websocket.py:392:15: W0718: Catching too general exception BaseException (broad-exception-caught)
api/websocket.py:418:19: W0718: Catching too general exception Exception (broad-exception-caught)
api/websocket.py:412:27: W0718: Catching too general exception BaseException (broad-exception-caught)
api/websocket.py:466:19: W0718: Catching too general exception BaseException (broad-exception-caught)
api/websocket.py:532:19: W0718: Catching too general exception BaseException (broad-exception-caught)
api/websocket.py:564:15: W0718: Catching too general exception Exception (broad-exception-caught)
api/websocket.py:572:0: C0103: Constant name "_ws_server" doesn't conform to UPPER_CASE naming style (invalid-name)
api/websocket.py:582:4: W0603: Using the global statement (global-statement)
api/websocket.py:10:0: W0611: Unused List imported from typing (unused-import)
api/websocket.py:10:0: W0611: Unused Optional imported from typing (unused-import)
************* Module New-test.api.api_server
api/api_server.py:1:0: C0302: Too many lines in module (2337/1000) (too-many-lines)
api/api_server.py:1:0: C0114: Missing module docstring (missing-module-docstring)
api/api_server.py:10:0: E0401: Unable to import 'jwt' (import-error)
api/api_server.py:11:0: E0401: Unable to import 'uvicorn' (import-error)
api/api_server.py:12:0: E0401: Unable to import 'fastapi' (import-error)
api/api_server.py:21:0: E0401: Unable to import 'fastapi.middleware.cors' (import-error)
api/api_server.py:22:0: E0401: Unable to import 'fastapi.responses' (import-error)
api/api_server.py:23:0: E0401: Unable to import 'fastapi.security' (import-error)
api/api_server.py:24:0: E0401: Unable to import 'project.backtesting.backtester' (import-error)
api/api_server.py:25:0: E0401: Unable to import 'project.config.configuration' (import-error)
api/api_server.py:26:0: E0401: Unable to import 'project.data.database' (import-error)
api/api_server.py:27:0: E0401: Unable to import 'project.exchange.exchange_manager' (import-error)
api/api_server.py:28:0: E0401: Unable to import 'project.trading.strategy_base' (import-error)
api/api_server.py:29:0: E0401: Unable to import 'project.trading.trading_bot' (import-error)
api/api_server.py:30:0: E0401: Unable to import 'project.utils.logging_utils' (import-error)
api/api_server.py:31:0: E0401: Unable to import 'project.utils.notify' (import-error)
api/api_server.py:32:0: E0401: Unable to import 'project.visualization.data_visualizer' (import-error)
api/api_server.py:33:0: E0401: Unable to import 'pydantic' (import-error)
api/api_server.py:40:0: C0115: Missing class docstring (missing-class-docstring)
api/api_server.py:40:0: R0903: Too few public methods (0/2) (too-few-public-methods)
api/api_server.py:45:0: C0115: Missing class docstring (missing-class-docstring)
api/api_server.py:45:0: R0903: Too few public methods (0/2) (too-few-public-methods)
api/api_server.py:51:0: C0115: Missing class docstring (missing-class-docstring)
api/api_server.py:51:0: R0903: Too few public methods (0/2) (too-few-public-methods)
api/api_server.py:58:0: C0115: Missing class docstring (missing-class-docstring)
api/api_server.py:58:0: R0903: Too few public methods (0/2) (too-few-public-methods)
api/api_server.py:63:0: C0115: Missing class docstring (missing-class-docstring)
api/api_server.py:63:0: R0903: Too few public methods (0/2) (too-few-public-methods)
api/api_server.py:88:0: C0115: Missing class docstring (missing-class-docstring)
api/api_server.py:88:0: R0903: Too few public methods (0/2) (too-few-public-methods)
api/api_server.py:105:0: C0115: Missing class docstring (missing-class-docstring)
api/api_server.py:105:0: R0903: Too few public methods (0/2) (too-few-public-methods)
api/api_server.py:123:0: R0902: Too many instance attributes (19/7) (too-many-instance-attributes)
api/api_server.py:126:23: W0621: Redefining name 'config' from outer scope (line 2329) (redefined-outer-name)
api/api_server.py:199:4: R0914: Too many local variables (17/15) (too-many-locals)
api/api_server.py:253:31: E0602: Undefined variable 'market_data' (undefined-variable)
api/api_server.py:257:16: W0707: Consider explicitly re-raising using 'raise HTTPException(status_code=500, detail='Ошибка при получении данных тикера') from e' (raise-missing-from)
api/api_server.py:291:19: W0718: Catching too general exception Exception (broad-exception-caught)
api/api_server.py:283:33: E0602: Undefined variable 'system_stats' (undefined-variable)
api/api_server.py:284:36: E1101: Instance of 'APIServer' has no 'get_memory_usage' member (no-member)
api/api_server.py:285:34: E0602: Undefined variable 'system_stats' (undefined-variable)
api/api_server.py:286:30: E0602: Undefined variable 'system_stats' (undefined-variable)
api/api_server.py:287:31: E0602: Undefined variable 'system_stats' (undefined-variable)
api/api_server.py:293:23: E0602: Undefined variable 'json_response' (undefined-variable)
api/api_server.py:279:40: W0613: Unused argument 'request' (unused-argument)
api/api_server.py:343:12: C0415: Import outside toplevel (psutil) (import-outside-toplevel)
api/api_server.py:342:29: W0613: Unused argument 'self' (unused-argument)
api/api_server.py:199:4: R0915: Too many statements (79/50) (too-many-statements)
api/api_server.py:342:8: W0612: Unused variable 'get_memory_usage' (unused-variable)
api/api_server.py:378:19: W0718: Catching too general exception BaseException (broad-exception-caught)
api/api_server.py:375:12: W0612: Unused variable 'bot_id' (unused-variable)
api/api_server.py:430:15: W0718: Catching too general exception Exception (broad-exception-caught)
api/api_server.py:423:23: W0718: Catching too general exception Exception (broad-exception-caught)
api/api_server.py:423:16: W0612: Unused variable 'e' (unused-variable)
api/api_server.py:452:15: W0718: Catching too general exception Exception (broad-exception-caught)
api/api_server.py:443:27: W0718: Catching too general exception Exception (broad-exception-caught)
api/api_server.py:442:34: W0212: Access to a protected member _save_state of a client class (protected-access)
api/api_server.py:438:20: W0612: Unused variable 'bot_id' (unused-variable)
api/api_server.py:443:20: W0612: Unused variable 'e' (unused-variable)
api/api_server.py:485:12: W0707: Consider explicitly re-raising using 'except Exception as exc' and 'raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail='Invalid token', headers={'WWW-Authenticate': 'Bearer'}) from exc' (raise-missing-from)
api/api_server.py:607:14: W0613: Unused argument 'user_credentials' (unused-argument)
api/api_server.py:607:49: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:623:34: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:639:32: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:663:32: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:690:8: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:718:8: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:779:23: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
api/api_server.py:743:50: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:793:8: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:819:32: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:846:45: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:875:8: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:907:8: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:932:4: R0913: Too many arguments (7/5) (too-many-arguments)
api/api_server.py:932:4: R0917: Too many positional arguments (7/5) (too-many-positional-arguments)
api/api_server.py:939:8: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:968:35: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:1036:12: W0707: Consider explicitly re-raising using 'raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f'Strategy {strategy_id} not found: {str(e)}') from e' (raise-missing-from)
api/api_server.py:1000:32: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:1066:12: W0707: Consider explicitly re-raising using 'raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f'Error getting strategy parameters: {str(e)}') from e' (raise-missing-from)
api/api_server.py:1042:32: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:1111:12: W0707: Consider explicitly re-raising using 'raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f'Error saving strategy parameters: {str(e)}') from e' (raise-missing-from)
api/api_server.py:1075:8: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:1116:29: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:1158:12: W0621: Redefining name 'config' from outer scope (line 2329) (redefined-outer-name)
api/api_server.py:1177:27: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
api/api_server.py:1181:12: W0707: Consider explicitly re-raising using 'raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f'Error creating bot: {str(e)}') from e' (raise-missing-from)
api/api_server.py:1144:37: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:1186:41: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:1208:27: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:1235:43: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:1258:42: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:1281:43: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:1305:27: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:1330:27: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:1398:27: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
api/api_server.py:1403:12: W0707: Consider explicitly re-raising using 'raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f'Error starting backtest: {str(e)}') from e' (raise-missing-from)
api/api_server.py:1372:8: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:1509:15: W0718: Catching too general exception Exception (broad-exception-caught)
api/api_server.py:1438:12: C0415: Import outside toplevel (pandas) (import-outside-toplevel)
api/api_server.py:1509:8: W0612: Unused variable 'e' (unused-variable)
api/api_server.py:1537:12: W0707: Consider explicitly re-raising using 'raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f'Error getting backtest results: {str(e)}') from e' (raise-missing-from)
api/api_server.py:1514:31: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:1580:12: W0707: Consider explicitly re-raising using 'raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f'Error getting backtest result: {str(e)}') from e' (raise-missing-from)
api/api_server.py:1543:32: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:1623:27: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
api/api_server.py:1628:12: W0707: Consider explicitly re-raising using 'raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f'Error starting optimization: {str(e)}') from e' (raise-missing-from)
api/api_server.py:1589:8: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:1633:4: R0914: Too many local variables (16/15) (too-many-locals)
api/api_server.py:1748:15: W0718: Catching too general exception Exception (broad-exception-caught)
api/api_server.py:1664:12: C0415: Import outside toplevel (pandas) (import-outside-toplevel)
api/api_server.py:1692:12: E0401: Unable to import 'project.optimization.genetic_optimizer' (import-error)
api/api_server.py:1692:12: C0415: Import outside toplevel (project.optimization.genetic_optimizer.GeneticOptimizer) (import-outside-toplevel)
api/api_server.py:1732:12: W0612: Unused variable 'response' (unused-variable)
api/api_server.py:1794:12: W0707: Consider explicitly re-raising using 'raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f'Error getting optimization tasks: {str(e)}') from e' (raise-missing-from)
api/api_server.py:1761:14: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:1825:12: W0707: Consider explicitly re-raising using 'raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f'Error getting optimization task: {str(e)}') from e' (raise-missing-from)
api/api_server.py:1800:28: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:1860:12: W0707: Consider explicitly re-raising using 'raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f'Error cancelling optimization task: {str(e)}') from e' (raise-missing-from)
api/api_server.py:1831:28: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:1889:12: W0707: Consider explicitly re-raising using 'raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f'Error getting optimization results: {str(e)}') from e' (raise-missing-from)
api/api_server.py:1866:31: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:1932:12: W0707: Consider explicitly re-raising using 'raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f'Error getting optimization result: {str(e)}') from e' (raise-missing-from)
api/api_server.py:1895:36: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:1937:4: R0913: Too many arguments (6/5) (too-many-arguments)
api/api_server.py:1937:4: R0917: Too many positional arguments (6/5) (too-many-positional-arguments)
api/api_server.py:1971:12: C0415: Import outside toplevel (pandas) (import-outside-toplevel)
api/api_server.py:1992:12: W0707: Consider explicitly re-raising using 'raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f'Error getting OHLC chart: {str(e)}') from e' (raise-missing-from)
api/api_server.py:1943:8: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:2027:20: C0415: Import outside toplevel (pandas) (import-outside-toplevel)
api/api_server.py:2052:12: W0707: Consider explicitly re-raising using 'raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f'Error getting equity chart: {str(e)}') from e' (raise-missing-from)
api/api_server.py:1998:32: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:2087:20: C0415: Import outside toplevel (pandas) (import-outside-toplevel)
api/api_server.py:2112:12: W0707: Consider explicitly re-raising using 'raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f'Error getting drawdown chart: {str(e)}') from e' (raise-missing-from)
api/api_server.py:2058:32: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:2147:20: C0415: Import outside toplevel (pandas) (import-outside-toplevel)
api/api_server.py:2172:12: W0707: Consider explicitly re-raising using 'raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f'Error getting monthly returns chart: {str(e)}') from e' (raise-missing-from)
api/api_server.py:2118:32: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:2207:20: C0415: Import outside toplevel (pandas) (import-outside-toplevel)
api/api_server.py:2230:12: W0707: Consider explicitly re-raising using 'raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f'Error getting optimization chart: {str(e)}') from e' (raise-missing-from)
api/api_server.py:2178:36: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:2247:12: W0621: Redefining name 'status' from outer scope (line 12) (redefined-outer-name)
api/api_server.py:2248:40: E1101: Instance of 'APIServer' has no 'start_time' member (no-member)
api/api_server.py:2263:12: W0707: Consider explicitly re-raising using 'raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f'Error getting system status: {str(e)}') from e' (raise-missing-from)
api/api_server.py:2235:38: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:2297:12: W0707: Consider explicitly re-raising using 'raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f'Error getting logs: {str(e)}') from e' (raise-missing-from)
api/api_server.py:2268:29: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:2322:12: W0707: Consider explicitly re-raising using 'raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f'Error sending notification: {str(e)}') from e' (raise-missing-from)
api/api_server.py:2303:40: W0613: Unused argument 'token' (unused-argument)
api/api_server.py:123:0: R0904: Too many public methods (48/20) (too-many-public-methods)
************* Module New-test.api.rest_api
api/rest_api.py:707:0: C0301: Line too long (127/100) (line-too-long)
api/rest_api.py:13:0: E0401: Unable to import 'aiohttp' (import-error)
api/rest_api.py:14:0: E0401: Unable to import 'jwt' (import-error)
api/rest_api.py:15:0: E0401: Unable to import 'aiohttp' (import-error)
api/rest_api.py:18:0: E0401: Unable to import 'project.config' (import-error)
api/rest_api.py:19:0: E0401: Unable to import 'project.data.market_data' (import-error)
api/rest_api.py:20:0: E0401: Unable to import 'project.trade_executor.order_executor' (import-error)
api/rest_api.py:21:0: E0401: Unable to import 'project.bots.bot_manager' (import-error)
api/rest_api.py:22:0: E0401: Unable to import 'project.bots.strategies.strategy_manager' (import-error)
api/rest_api.py:23:0: E0401: Unable to import 'project.bots.arbitrage.core' (import-error)
api/rest_api.py:24:0: E0401: Unable to import 'project.utils.logging_utils' (import-error)
api/rest_api.py:25:0: E0401: Unable to import 'project.utils.notify' (import-error)
api/rest_api.py:44:0: C0116: Missing function or method docstring (missing-function-docstring)
api/rest_api.py:70:15: W0718: Catching too general exception Exception (broad-exception-caught)
api/rest_api.py:115:11: W0718: Catching too general exception Exception (broad-exception-caught)
api/rest_api.py:148:11: W0718: Catching too general exception Exception (broad-exception-caught)
api/rest_api.py:178:11: W0718: Catching too general exception Exception (broad-exception-caught)
api/rest_api.py:223:11: W0718: Catching too general exception Exception (broad-exception-caught)
api/rest_api.py:288:11: W0718: Catching too general exception Exception (broad-exception-caught)
api/rest_api.py:307:11: W0718: Catching too general exception Exception (broad-exception-caught)
api/rest_api.py:351:11: W0718: Catching too general exception Exception (broad-exception-caught)
api/rest_api.py:384:11: W0718: Catching too general exception Exception (broad-exception-caught)
api/rest_api.py:360:20: W0613: Unused argument 'request' (unused-argument)
api/rest_api.py:410:11: W0718: Catching too general exception Exception (broad-exception-caught)
api/rest_api.py:429:8: W0621: Redefining name 'config' from outer scope (line 30) (redefined-outer-name)
api/rest_api.py:459:11: W0718: Catching too general exception Exception (broad-exception-caught)
api/rest_api.py:487:11: W0718: Catching too general exception Exception (broad-exception-caught)
api/rest_api.py:511:11: W0718: Catching too general exception Exception (broad-exception-caught)
api/rest_api.py:496:26: W0613: Unused argument 'request' (unused-argument)
api/rest_api.py:534:8: W0621: Redefining name 'config' from outer scope (line 30) (redefined-outer-name)
api/rest_api.py:561:11: W0718: Catching too general exception Exception (broad-exception-caught)
api/rest_api.py:589:11: W0718: Catching too general exception Exception (broad-exception-caught)
api/rest_api.py:615:11: W0718: Catching too general exception Exception (broad-exception-caught)
api/rest_api.py:660:11: W0718: Catching too general exception Exception (broad-exception-caught)
api/rest_api.py:739:11: W0718: Catching too general exception Exception (broad-exception-caught)
api/rest_api.py:666:0: R0911: Too many return statements (7/6) (too-many-return-statements)
api/rest_api.py:751:4: W0621: Redefining name 'app' from outer scope (line 775) (redefined-outer-name)
api/rest_api.py:749:4: E0401: Unable to import 'fastapi' (import-error)
api/rest_api.py:749:4: C0415: Import outside toplevel (fastapi.FastAPI) (import-outside-toplevel)
api/rest_api.py:756:23: E0602: Undefined variable 'router' (undefined-variable)
api/rest_api.py:757:23: E0602: Undefined variable 'strategy_router' (undefined-variable)
api/rest_api.py:758:23: E0602: Undefined variable 'market_router' (undefined-variable)
api/rest_api.py:759:23: E0602: Undefined variable 'user_router' (undefined-variable)
api/rest_api.py:762:23: E0602: Undefined variable 'ws_router' (undefined-variable)
api/rest_api.py:763:23: E0602: Undefined variable 'data_ws_router' (undefined-variable)
api/rest_api.py:764:23: E0602: Undefined variable 'auth_router' (undefined-variable)
api/rest_api.py:765:23: E0602: Undefined variable 'order_router' (undefined-variable)
api/rest_api.py:768:23: E0602: Undefined variable 'admin_router' (undefined-variable)
api/rest_api.py:769:23: E0602: Undefined variable 'stats_router' (undefined-variable)
api/rest_api.py:778:4: E0401: Unable to import 'uvicorn' (import-error)
api/rest_api.py:7:0: W0611: Unused import os (unused-import)
api/rest_api.py:9:0: W0611: Unused Dict imported from typing (unused-import)
api/rest_api.py:9:0: W0611: Unused Any imported from typing (unused-import)
api/rest_api.py:9:0: W0611: Unused Optional imported from typing (unused-import)
api/rest_api.py:13:0: W0611: Unused import aiohttp (unused-import)
************* Module New-test.infrastructure.database
infrastructure/database.py:18:0: E0401: Unable to import 'project.config' (import-error)
infrastructure/database.py:19:0: E0401: Unable to import 'project.utils.error_handler' (import-error)
infrastructure/database.py:20:0: E0401: Unable to import 'project.utils.logging_utils' (import-error)
************* Module New-test.infrastructure.message_broker
infrastructure/message_broker.py:10:0: E0401: Unable to import 'project.config' (import-error)
infrastructure/message_broker.py:11:0: E0401: Unable to import 'project.utils.error_handler' (import-error)
infrastructure/message_broker.py:12:0: E0401: Unable to import 'project.utils.logging_utils' (import-error)
infrastructure/message_broker.py:118:15: W0718: Catching too general exception Exception (broad-exception-caught)
infrastructure/message_broker.py:99:18: E1101: Instance of 'bool' has no 'basic_publish' member (no-member)
infrastructure/message_broker.py:112:27: W0718: Catching too general exception Exception (broad-exception-caught)
infrastructure/message_broker.py:155:15: W0718: Catching too general exception Exception (broad-exception-caught)
infrastructure/message_broker.py:186:15: W0718: Catching too general exception Exception (broad-exception-caught)
infrastructure/message_broker.py:200:19: W0718: Catching too general exception Exception (broad-exception-caught)
************* Module New-test.infrastructure.cache_service
infrastructure/cache_service.py:10:0: E0401: Unable to import 'project.config' (import-error)
infrastructure/cache_service.py:11:0: E0401: Unable to import 'project.utils.error_handler' (import-error)
infrastructure/cache_service.py:12:0: E0401: Unable to import 'project.utils.logging_utils' (import-error)
infrastructure/cache_service.py:106:23: W0718: Catching too general exception Exception (broad-exception-caught)
infrastructure/cache_service.py:150:18: E1101: Instance of 'CacheService' has no 'redis' member (no-member)
infrastructure/cache_service.py:251:45: C0201: Consider iterating the dictionary directly instead of calling .keys() (consider-iterating-dictionary)
************* Module New-test.technical_analysis.signal_generator
technical_analysis/signal_generator.py:20:0: E0401: Unable to import 'project.technical_analysis.indicators' (import-error)
technical_analysis/signal_generator.py:21:0: E0401: Unable to import 'project.utils.error_handler' (import-error)
technical_analysis/signal_generator.py:22:0: E0401: Unable to import 'project.utils.logging_utils' (import-error)
technical_analysis/signal_generator.py:7:0: W0611: Unused Any imported from typing (unused-import)
technical_analysis/signal_generator.py:7:0: W0611: Unused Union imported from typing (unused-import)
technical_analysis/signal_generator.py:7:0: W0611: Unused Tuple imported from typing (unused-import)
************* Module New-test.technical_analysis.patterns
technical_analysis/patterns.py:23:0: E0401: Unable to import 'project.technical_analysis.indicators' (import-error)
technical_analysis/patterns.py:24:0: E0401: Unable to import 'project.utils.error_handler' (import-error)
technical_analysis/patterns.py:25:0: E0401: Unable to import 'project.utils.logging_utils' (import-error)
technical_analysis/patterns.py:462:42: W0613: Unused argument 'threshold' (unused-argument)
technical_analysis/patterns.py:538:8: W0101: Unreachable code (unreachable)
technical_analysis/patterns.py:751:16: W0612: Unused variable 'first_body_size' (unused-variable)
technical_analysis/patterns.py:806:16: W0612: Unused variable 'first_body_size' (unused-variable)
technical_analysis/patterns.py:500:4: R0915: Too many statements (80/50) (too-many-statements)
technical_analysis/patterns.py:500:45: W0613: Unused argument 'threshold' (unused-argument)
technical_analysis/patterns.py:19:4: C0412: Imports from package numpy are not grouped (ungrouped-imports)
technical_analysis/patterns.py:20:4: C0412: Imports from package pandas are not grouped (ungrouped-imports)
technical_analysis/patterns.py:7:0: W0611: Unused import logging (unused-import)
technical_analysis/patterns.py:8:0: W0611: Unused Any imported from typing (unused-import)
technical_analysis/patterns.py:8:0: W0611: Unused Dict imported from typing (unused-import)
technical_analysis/patterns.py:8:0: W0611: Unused List imported from typing (unused-import)
technical_analysis/patterns.py:8:0: W0611: Unused Optional imported from typing (unused-import)
technical_analysis/patterns.py:8:0: W0611: Unused Tuple imported from typing (unused-import)
technical_analysis/patterns.py:8:0: W0611: Unused Union imported from typing (unused-import)
technical_analysis/patterns.py:12:4: W0611: Unused numpy imported as np (unused-import)
technical_analysis/patterns.py:23:0: W0611: Unused Indicators imported from project.technical_analysis.indicators (unused-import)
************* Module New-test.technical_analysis.indicators
technical_analysis/indicators.py:22:0: E0401: Unable to import 'project.utils.cache_utils' (import-error)
technical_analysis/indicators.py:23:0: E0401: Unable to import 'project.utils.error_handler' (import-error)
technical_analysis/indicators.py:24:0: E0401: Unable to import 'project.utils.logging_utils' (import-error)
technical_analysis/indicators.py:245:4: R0914: Too many local variables (17/15) (too-many-locals)
technical_analysis/indicators.py:18:4: C0412: Imports from package numpy are not grouped (ungrouped-imports)
technical_analysis/indicators.py:19:4: C0412: Imports from package pandas are not grouped (ungrouped-imports)
technical_analysis/indicators.py:7:0: W0611: Unused Any imported from typing (unused-import)
technical_analysis/indicators.py:7:0: W0611: Unused List imported from typing (unused-import)
technical_analysis/indicators.py:7:0: W0611: Unused Optional imported from typing (unused-import)
technical_analysis/indicators.py:7:0: W0611: Unused Tuple imported from typing (unused-import)
technical_analysis/indicators.py:7:0: W0611: Unused Union imported from typing (unused-import)
technical_analysis/indicators.py:11:4: W0611: Unused numpy imported as np (unused-import)
technical_analysis/indicators.py:22:0: W0611: Unused cache imported from project.utils.cache_utils (unused-import)
************* Module New-test.integrations.binance_liquidations
integrations/binance_liquidations.py:185:0: C0301: Line too long (110/100) (line-too-long)
integrations/binance_liquidations.py:11:0: E0401: Unable to import 'websockets' (import-error)
integrations/binance_liquidations.py:12:0: E0401: Unable to import 'project.config' (import-error)
integrations/binance_liquidations.py:13:0: E0401: Unable to import 'project.infrastructure.database' (import-error)
integrations/binance_liquidations.py:14:0: E0401: Unable to import 'project.utils.error_handler' (import-error)
integrations/binance_liquidations.py:15:0: E0401: Unable to import 'project.utils.logging_utils' (import-error)
integrations/binance_liquidations.py:16:0: E0401: Unable to import 'project.utils.notify' (import-error)
integrations/binance_liquidations.py:24:0: R0902: Too many instance attributes (8/7) (too-many-instance-attributes)
integrations/binance_liquidations.py:173:19: W0718: Catching too general exception Exception (broad-exception-caught)
integrations/binance_liquidations.py:167:27: W0718: Catching too general exception Exception (broad-exception-caught)
integrations/binance_liquidations.py:165:20: W0612: Unused variable 'e' (unused-variable)
integrations/binance_liquidations.py:260:15: W0718: Catching too general exception Exception (broad-exception-caught)
integrations/binance_liquidations.py:255:23: W0718: Catching too general exception Exception (broad-exception-caught)
integrations/binance_liquidations.py:260:8: W0612: Unused variable 'e' (unused-variable)
integrations/binance_liquidations.py:274:15: W0718: Catching too general exception Exception (broad-exception-caught)
integrations/binance_liquidations.py:274:8: W0612: Unused variable 'e' (unused-variable)
integrations/binance_liquidations.py:300:15: W0718: Catching too general exception Exception (broad-exception-caught)
integrations/binance_liquidations.py:300:8: W0612: Unused variable 'e' (unused-variable)
integrations/binance_liquidations.py:334:15: W0718: Catching too general exception Exception (broad-exception-caught)
integrations/binance_liquidations.py:319:12: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
integrations/binance_liquidations.py:334:8: W0612: Unused variable 'e' (unused-variable)
************* Module New-test.integrations.email_sender
integrations/email_sender.py:14:0: E0401: Unable to import 'project.config' (import-error)
integrations/email_sender.py:15:0: E0401: Unable to import 'project.utils.error_handler' (import-error)
integrations/email_sender.py:16:0: E0401: Unable to import 'project.utils.logging_utils' (import-error)
integrations/email_sender.py:78:4: R0913: Too many arguments (6/5) (too-many-arguments)
integrations/email_sender.py:78:4: R0917: Too many positional arguments (6/5) (too-many-positional-arguments)
integrations/email_sender.py:133:23: W0718: Catching too general exception Exception (broad-exception-caught)
integrations/email_sender.py:165:15: W0718: Catching too general exception Exception (broad-exception-caught)
************* Module New-test.integrations.rest_api
integrations/rest_api.py:9:0: E0401: Unable to import 'jwt' (import-error)
integrations/rest_api.py:10:0: E0401: Unable to import 'aiohttp' (import-error)
integrations/rest_api.py:11:0: E0401: Unable to import 'project.config' (import-error)
integrations/rest_api.py:12:0: E0401: Unable to import 'project.utils.error_handler' (import-error)
integrations/rest_api.py:13:0: E0401: Unable to import 'project.utils.logging_utils' (import-error)
integrations/rest_api.py:18:0: R0902: Too many instance attributes (8/7) (too-many-instance-attributes)
integrations/rest_api.py:127:8: E0401: Unable to import 'project.bots.strategies.strategy_manager' (import-error)
integrations/rest_api.py:127:8: C0415: Import outside toplevel (project.bots.strategies.strategy_manager.StrategyManager) (import-outside-toplevel)
integrations/rest_api.py:168:33: W0613: Unused argument 'request' (unused-argument)
integrations/rest_api.py:174:8: E0401: Unable to import 'project' (import-error)
integrations/rest_api.py:174:8: C0415: Import outside toplevel (project.__version__) (import-outside-toplevel)
integrations/rest_api.py:172:32: W0613: Unused argument 'request' (unused-argument)
integrations/rest_api.py:180:35: W0613: Unused argument 'request' (unused-argument)
integrations/rest_api.py:273:15: W0718: Catching too general exception Exception (broad-exception-caught)
integrations/rest_api.py:306:15: W0718: Catching too general exception Exception (broad-exception-caught)
integrations/rest_api.py:340:15: W0718: Catching too general exception Exception (broad-exception-caught)
integrations/rest_api.py:321:12: E0401: Unable to import 'project.utils.ccxt_exchanges' (import-error)
integrations/rest_api.py:321:12: C0415: Import outside toplevel (project.utils.ccxt_exchanges.connect_exchange, project.utils.ccxt_exchanges.fetch_closed_orders, project.utils.ccxt_exchanges.fetch_open_orders) (import-outside-toplevel)
integrations/rest_api.py:327:12: W0612: Unused variable 'exchange' (unused-variable)
integrations/rest_api.py:346:4: R0914: Too many local variables (16/15) (too-many-locals)
integrations/rest_api.py:407:15: W0718: Catching too general exception Exception (broad-exception-caught)
integrations/rest_api.py:373:12: E0401: Unable to import 'project.trade_executor.order_executor' (import-error)
integrations/rest_api.py:373:12: C0415: Import outside toplevel (project.trade_executor.order_executor.OrderExecutor) (import-outside-toplevel)
integrations/rest_api.py:435:15: W0718: Catching too general exception Exception (broad-exception-caught)
integrations/rest_api.py:427:12: E0401: Unable to import 'project.utils.ccxt_exchanges' (import-error)
integrations/rest_api.py:427:12: C0415: Import outside toplevel (project.utils.ccxt_exchanges.cancel_order) (import-outside-toplevel)
integrations/rest_api.py:454:15: W0718: Catching too general exception Exception (broad-exception-caught)
integrations/rest_api.py:448:12: E0401: Unable to import 'project.utils.ccxt_exchanges' (import-error)
integrations/rest_api.py:448:12: C0415: Import outside toplevel (project.utils.ccxt_exchanges.fetch_ticker) (import-outside-toplevel)
integrations/rest_api.py:489:15: W0718: Catching too general exception Exception (broad-exception-caught)
integrations/rest_api.py:469:12: E0401: Unable to import 'project.utils.ccxt_exchanges' (import-error)
integrations/rest_api.py:469:12: C0415: Import outside toplevel (project.utils.ccxt_exchanges.fetch_ohlcv) (import-outside-toplevel)
************* Module New-test.integrations.slack_integration
integrations/slack_integration.py:9:0: E0401: Unable to import 'project.config' (import-error)
integrations/slack_integration.py:10:0: E0401: Unable to import 'project.utils.error_handler' (import-error)
integrations/slack_integration.py:11:0: E0401: Unable to import 'project.utils.logging_utils' (import-error)
integrations/slack_integration.py:12:0: E0401: Unable to import 'slack_sdk.errors' (import-error)
integrations/slack_integration.py:13:0: E0401: Unable to import 'slack_sdk.web.async_client' (import-error)
integrations/slack_integration.py:61:4: R0913: Too many arguments (6/5) (too-many-arguments)
integrations/slack_integration.py:61:4: R0917: Too many positional arguments (6/5) (too-many-positional-arguments)
integrations/slack_integration.py:102:15: W0718: Catching too general exception Exception (broad-exception-caught)
integrations/slack_integration.py:142:15: W0718: Catching too general exception Exception (broad-exception-caught)
integrations/slack_integration.py:190:15: W0718: Catching too general exception Exception (broad-exception-caught)
integrations/slack_integration.py:224:15: W0718: Catching too general exception Exception (broad-exception-caught)
integrations/slack_integration.py:221:8: W0612: Unused variable 'e' (unused-variable)
integrations/slack_integration.py:260:4: R0913: Too many arguments (8/5) (too-many-arguments)
integrations/slack_integration.py:260:4: R0917: Too many positional arguments (8/5) (too-many-positional-arguments)
************* Module New-test.integrations.trading_view_webhooks
integrations/trading_view_webhooks.py:12:0: E0401: Unable to import 'aiohttp' (import-error)
integrations/trading_view_webhooks.py:13:0: E0401: Unable to import 'project.bots.strategies.strategy_manager' (import-error)
integrations/trading_view_webhooks.py:14:0: E0401: Unable to import 'project.config' (import-error)
integrations/trading_view_webhooks.py:15:0: E0401: Unable to import 'project.utils.error_handler' (import-error)
